services:
  - type: web
    name: ytvidtrans-backend
    env: python
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    autoDeploy: true
    plan: free
