services:
  - type: web
    name: tts-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    autoDeploy: true
    plan: free
